insert into products(name,serial,category,quantity,price) values ('Jablko','1234','Owoce',100,2)
insert into products(name,serial,category,quantity,price) values ('Klawiatura','1248','Akcesoria komputerowe',20,50)
insert into products(name,serial,category,quantity,price) values ('Zeszyt','1242','Produkty szkolne',400,10.5)
insert into products(name,serial,category,quantity,price) values ('Cukierek','1240','Slodycze',400,0.5)
insert into products(name,serial,category,quantity,price) values ('Cola','1235','Napoje',200,4.5)
insert into products(name,serial,category,quantity,price) values ('Banan','1235','Owoce',200,3)
insert into products(name,serial,category,quantity,price) values ('Zeszyt','1242','Produkty szkolne',400,10.5)
insert into products(name,serial,category,quantity,price) values ('Pomidor','1238','Warzywa',400,3.5)
insert into products(name,serial,category,quantity,price) values ('Dlugopis','1243','Produkty szkolne',400,7.5)
insert into products(name,serial,category,quantity,price) values ('Lizak','1241','Slodycze',400,0.5)
insert into products(name,serial,category,quantity,price) values ('Woda','1241','Napoje',400,1.5)
insert into products(name,serial,category,quantity,price) values ('Wisnia','1236','Owoce',200,2.5)
insert into products(name,serial,category,quantity,price) values ('Marchew','1237','Warzywa',200,1.5)
insert into products(name,serial,category,quantity,price) values ('Skrzynia biegow','1246','Czesci samochodowe',20,3000)
insert into products(name,serial,category,quantity,price) values ('Monitor','1247','Akcesoria komputerowe',20,700)
insert into products(name,serial,category,quantity,price) values ('Dynia','1238','Warzywa',400,3.5)
insert into products(name,serial,category,quantity,price) values ('Czekolada','1239','Slodycze',400,7.5)
insert into products(name,serial,category,quantity,price) values ('Kolo','1245','Czesci samochodowe',400,300)
insert into products(name,serial,category,quantity,price) values ('Zeszyt','1242','Produkty szkolne',400,10.5)
insert into products(name,serial,category,quantity,price) values ('Notatnik','1243','Produkty szkolne',400,7.5)
insert into products(name,serial,category,quantity,price) values ('Olowek','1244','Produkty szkolne',400,2.5)
insert into products(name,serial,category,quantity,price) values ('Kolo','1245','Czesci samochodowe',400,300)
insert into products(name,serial,category,quantity,price) values ('Mysz','1249','Akcesoria komputerowe',40,30)

